### ISSUE TITLE
Multiple Command Bus support

### ISSUE THREAD

**Issue by rosstuck** [xtrasmal/TacticianBundle#6]
There's been a lot of offline discussion about supporting multiple command buses more easily. I'm thinking of a syntax like the following:

``` yml
tactician:
    default: # maps to the default tactician.commandbus service
        method_inflector: "tactician.handler.inflector.handle"
        handler_locator: "tactician.handler.locator.symfony"
        middleware:
            - my.app.custom.middleware
            - tactician.some.standard.middleware1
            - tactician.some.standard.middleware2
    job_queue:  # dynamically creates new service tactician.commandbus.job_queue
        method_inflector: "tactician.handler.inflector.handle"
        handler_locator: "some.custom.one"
        middleware:
            - my.app.custom.middleware
            - tactician.some.standard.middleware3
```

Questions:
- Does that make sense to folks?
- Should the dynamic buses extend the options set in default or not? (since that refers to an actual command bus instance and not just a generic options bag, that could get confusing. Maybe split default options and default command bus instance)
- Should we nest them all under a `buses` key or similar?
- Are there other options we should support?

**Comment by rosstuck** [comment]
On second thought, we really should nest them because we likely want some other 2nd level keys for optional plugin packages, like queuing or doctrine transactions.

**Comment by rdohms** [comment]
My 2 cents.
- yes, nest them under `buses`
- make `default` a property, and allow us to give any names we wish, but then alias the `tactician.commandbus` service to the default bus. Allows us to use meaningful names to hint at their uses in the app. (or just assume if there is one, it is the default)
- That leaves you to use `default` as a sibling of `buses` and be all about the default config.

**Comment by rtuin** [comment]
+1 for nesting the bus definitions. 

Assuming the the (generated) bus names are in the format of `tactician.commandbus.busname` I suggest to nest them under "commandbus". Like so:

``` yaml
tactician:
    commandbus:
        default:
            # ...
        job_queue:
            # ...
```

The `method_inflector` and `handler_locator` should not be under these definitions as they are specific to the `CommandHandlerMiddleware`.
